bundler_args: --without development testext production
rvm:
  - "jruby-19mode"
  - "jruby-head"
env:
  - JRUBY_OPTS="--client -Xcext.enabled=false"
before_script:
  - psql -c 'create database eggshell_test;' -U postgres
