cas_server: 'localhost:1234/cas'
cas_logout_url: 'https://localhost:4321/cas/logout'
canvas_proxy:
  admin_access_token: "someMumboJumbo"
  canvas_root: "http://localhost:12345"
  fake: false
campusdb:
  adapter: jdbch2
  url: jdbc:h2:mem:h2CampusDataSource;DB_CLOSE_DELAY=-1;MODE=Oracle
  username: sa
  password: sa

postgres:
  database: eggshell_production
  username: eggshell_production
  password: secret
  host: localhost
  port: 5432

freshen_vcr: <%= ENV['freshen_vcr'] %>
